name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - frontend
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - frontend

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Choose the Node.js version that matches your project
      - name: Install Dependencies
        run: npm install
      - name: Build Application
        run: npm run build
      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_GROUND_0AF911310 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "build"  # Adjust based on your build output location
          api_location: ""
          output_location: "build"
